### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Alexander-Cui** [Alexander-Cui/Shopic#18]

**Comment by Alexander-Cui** [comment]
Error happens when I call the /segment endpoint
passing filename and id. Error from sa.isolate_apparel


```
Traceback (most recent call last):
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Github\SHOPIC\Shopic\flask_shopic\venv\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\app.py", line 130, in segment
    new_img = sa.isolate_apparel(img, segmap, id_) #(key of dictionary)
  File "D:\Github\SHOPIC\Shopic\flask_shopic\sama_api.py", line 106, in isolate_apparel
    if segmap[i][j] != False:
IndexError: too many indices for array
```
